# Site settings
title: Charpi - dessins, caricatures, Spaß
email: contact@charpi.fr
description: >
  Ce site regroupe des dessins, des têtes surtout.
  Leur auteur s'est dit que l'Internet mondial était l'endroit parfait
  pour les diffuser.
baseurl: ""
#url: "http://localhost:4000"
url: "http://www.charpi.fr"
paginate: 16
defaults:
  -
    scope:
      path: ""
    values:
      kind: "drawing" # others are "home" or "others" for now

exclude: [README.md, deploy.sh]

# Build settings
markdown: kramdown
